### ISSUE TITLE
Not really an issue just an idea.

### ISSUE THREAD

**Issue by Hlqb4o** [Shichiha/QuickNurse#1]
Is there any way for you to make the mod 1.4.3 compatible? I would upgrade to 1.4.4 but im doing a calamity playthrough and calamity isnt supported there yet. Thanks in advance!

**Comment by Shichiha** [comment]
I published the mod for 1.4.4 since calamity is supported there, though calamity modifies Nurse Healing Prices, and I haven't accommodated for that.

--sorry for the year later reply xd, and no, I won't be making a backport to 1.4.3 since calamity supports 1.4.4 now a year later anyway

**Comment by Shichiha** [comment]
added temporary untested calamity support but should be working 🥱
